// Generated by Discord Bot Builder
require('dotenv').config();
const { Client, GatewayIntentBits } = require('discord.js');

const client = new Client({
  intents: [GatewayIntentBits.Guilds, GatewayIntentBits.GuildMessages, GatewayIntentBits.MessageContent],
});

// Variable stores
const globalVars = new Map();
const guildVars = new Map();
const userVars = new Map();
const channelVars = new Map();

// Music player setup
const { Player } = require('discord-player');
const player = new Player(client);
player.extractors.loadDefault().catch(console.error);

client.on('interactionCreate', async (interaction) => {
  try {
    const res_getUserInfo_1776383037928 = interaction?.voice?.channel;
    if (res_getUserInfo_1776383037928) {
    } else {
    }
    // Play music using discord-player
    const { useMainPlayer } = require('discord-player');
    const player = useMainPlayer();
    const voiceChannel = (typeof res_getUserInfo_1776383037928 !== 'undefined' ? (res_getUserInfo_1776383037928?.id || res_getUserInfo_1776383037928) : null);
    if (!voiceChannel) { await (interaction || message).reply('You need to be in a voice channel!'); }
    else {
      try {
        const { track } = await player.play(voiceChannel, "", {
          nodeOptions: { metadata: { channel: interaction?.channel || message?.channel } }
        });
        await (interaction ? interaction.reply(`🎶 Now playing: **${track.title}**`) : message.reply(`🎶 Now playing: **${track.title}**`));
      } catch(e) { await (interaction || message).reply('❌ Could not play: ' + e.message); }
    }
  } catch (error) {
    console.error('[Bot Error]', error);
  }
});

client.login(process.env.DISCORD_TOKEN).catch(err => {
  console.error('[Login Error]', err.message);
  if (err.message.includes('disallowed intents')) {
    console.error('======================================================================');
    console.error('🚨 PRIVILEGED INTENTS MISSING 🚨');
    console.error('======================================================================');
    console.error('Your bot is missing Privileged Gateway Intents! To fix this:');
    console.error('1. Go to the Discord Developer Portal -> https://discord.com/developers/applications');
    console.error('2. Select your application and click "Bot" in the left sidebar.');
    console.error('3. Scroll down to the "Privileged Gateway Intents" section.');
    console.error('4. ENABLE all toggle switches (Presence Intent, Server Members Intent, Message Content Intent).');
    console.error('5. Click "Save Changes" and run your bot again.');
    console.error('======================================================================');
  }
});

