import { generateBotCode } from '../utils/codeGenerator.js';
import archiver from 'archiver';

export function previewCode(req, res) {
  try {
    const { nodes = [], edges = [], settings = {} } = req.body;

    const code = generateBotCode(nodes, edges, {
      prefix: settings.bot_prefix || '!',
      intents: settings.intents || ['Guilds', 'GuildMessages', 'MessageContent'],
      activityType: settings.activity_type || 'Playing',
      activityText: settings.activity_text || '',
    });

    res.json({ code });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
}

export function exportZip(req, res) {
  try {
    const { name = 'my-bot', description = '', nodes = [], edges = [], settings = {} } = req.body;
    const token = settings.bot_token || '';

    const code = generateBotCode(nodes, edges, {
      prefix: settings.bot_prefix || '!',
      intents: settings.intents || ['Guilds', 'GuildMessages', 'MessageContent'],
      activityType: settings.activity_type || 'Playing',
      activityText: settings.activity_text || '',
    });

    // Set headers for zip download
    const safeName = (name || 'my-bot').replace(/[^a-zA-Z0-9-_]/g, '-').toLowerCase();
    res.set({
      'Content-Type': 'application/zip',
      'Content-Disposition': `attachment; filename="${safeName}.zip"`,
    });

    const archive = archiver('zip', { zlib: { level: 9 } });
    archive.pipe(res);

    // Main bot file
    archive.append(code.indexJs, { name: 'index.js' });

    // Check if music blocks are used
    const usedTypes = new Set(nodes.map(n => n.type));
    const hasMusic = usedTypes.has('playMusic') || usedTypes.has('stopMusic') || usedTypes.has('skipMusic');
    const deps = {
      'discord.js': '^14.16.3',
      'dotenv': '^16.4.7',
    };
    if (hasMusic) {
      deps['discord-player'] = 'latest';
      deps['@discord-player/extractor'] = 'latest';
      deps['@vookav2/play-dl'] = 'latest';
      deps['@distube/ytdl-core'] = 'latest';
      deps['@discord-player/ffmpeg'] = 'latest';
    }

    // Package.json
    archive.append(JSON.stringify({
      name: safeName,
      version: '1.0.0',
      description: description || 'Discord bot generated by Discord Bot Builder',
      main: 'index.js',
      scripts: {
        start: 'node index.js',
        dev: 'node --watch index.js',
      },
      dependencies: deps,
    }, null, 2), { name: 'package.json' });

    // .env file with token
    archive.append(`DISCORD_TOKEN=${token || 'YOUR_BOT_TOKEN_HERE'}\n`, { name: '.env' });

    // .env.example
    archive.append(`DISCORD_TOKEN=YOUR_BOT_TOKEN_HERE\n`, { name: '.env.example' });

    // Commands folder
    if (code.commands && code.commands.length > 0) {
      for (const cmd of code.commands) {
        archive.append(cmd.content, { name: `commands/${cmd.name}.js` });
      }
    }

    // Events folder
    if (code.events && code.events.length > 0) {
      for (const evt of code.events) {
        archive.append(evt.content, { name: `events/${evt.name}.js` });
      }
    }

    // Utils
    if (code.utilsJs) {
      archive.append(code.utilsJs, { name: 'utils/variables.js' });
    }

    // README
    archive.append(`# ${name || 'My Discord Bot'}\n\nGenerated by Discord Bot Builder.\n\n## Setup\n\n\`\`\`bash\nnpm install\n\`\`\`\n\n## Important: Privileged Intents\nYour bot needs special permissions to read messages. Before starting:\n1. Go to the [Discord Developer Portal](https://discord.com/developers/applications)\n2. Select your application and go to the **Bot** tab.\n3. Scroll down to **Privileged Gateway Intents**.\n4. Enable **Message Content Intent**, **Server Members Intent**, and **Presence Intent**.\n5. Save changes.\n\nEdit \`.env\` and add your bot token, then:\n\n\`\`\`bash\nnpm start\n\`\`\`\n`, { name: 'README.md' });

    archive.finalize();
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
}
